// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbwzzvuyhphdtiwvqofs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5id3p6dnV5aHBoZHRpd3Zxb2ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODYzMjIsImV4cCI6MjA3MTg2MjMyMn0.zrq4VUExKtaKeDOBP0PrIoBQAf7y6MdOWoVHlC-E9Xo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});